name: gas_monitor
description: "Flutter gas monitoring app using MQTT with local alert notifications."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^10.11.9
  flutter_local_notifications: ^17.2.4
  permission_handler: ^11.4.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
